### ISSUE TITLE
请教一个关于预测（predict）的问题

### ISSUE THREAD

**Issue by uyoin** [kingglory/BERT-BILSTM-CRF-NER-Pytorch-Chinese#1]
我用您的代码进行了模型的训练，成功训练之后打算用predict.py代码进行预测的尝试
结果出现以下两个问题：
①输入文本过长似乎会发生“实体识别结果为空”的提示

②而输入较短的文本会提示访问huggingface的404，似乎我需要在huggingface上上传模型还是什么吗？

2023-01-24 15:21:36.106249: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "L:\BERT-BILSTM-CRF-NER-Pytorch-Chinese-main\torch_ner\source\predict.py", line 216, in <module>
    print(get_entities_result(sent))
  File "L:\BERT-BILSTM-CRF-NER-Pytorch-Chinese-main\torch_ner\source\predict.py", line 24, in get_entities_result
    sentence_list, predict_labels = predict(query, path)
  File "L:\BERT-BILSTM-CRF-NER-Pytorch-Chinese-main\torch_ner\source\predict.py", line 59, in predict
    tokenizer = BertTokenizer.from_pretrained(model_path)
  File "C:\Users\LENOVO\anaconda3\envs\BERT-BILSTM-CRF-NER-Pytorch-Chinese-main\lib\site-packages\transformers\tokenization_utils_base.py", line 1647, in from_pretrained
    fast_tokenizer_file = get_fast_tokenizer_file(
  File "C:\Users\LENOVO\anaconda3\envs\BERT-BILSTM-CRF-NER-Pytorch-Chinese-main\lib\site-packages\transformers\tokenization_utils_base.py", line 3408, in get_fast_tokenizer_file
    all_files = get_list_of_files(path_or_repo, revision=revision, use_auth_token=use_auth_token)
  File "C:\Users\LENOVO\anaconda3\envs\BERT-BILSTM-CRF-NER-Pytorch-Chinese-main\lib\site-packages\transformers\file_utils.py", line 1686, in get_list_of_files
    model_info = HfApi(endpoint=HUGGINGFACE_CO_RESOLVE_ENDPOINT).model_info(
  File "C:\Users\LENOVO\anaconda3\envs\BERT-BILSTM-CRF-NER-Pytorch-Chinese-main\lib\site-packages\huggingface_hub\hf_api.py", line 248, in model_info
    r.raise_for_status()
  File "C:\Users\LENOVO\anaconda3\envs\BERT-BILSTM-CRF-NER-Pytorch-Chinese-main\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/output/20221219153051

由于是刚入门的小白第一次跑项目，因此不太了解以上的报错，请大神指教，谢谢！

**Comment by WenSongWang** [comment]
> 我用您的代码进行了模型的训练，成功训练之后打算用predict.py代码进行预测的尝试 结果出现以下两个问题： ①输入文本过长似乎会发生“实体识别结果为空”的提示
> 
> ②而输入较短的文本会提示访问huggingface的404，似乎我需要在huggingface上上传模型还是什么吗？
> 
> 2023-01-24 15:21:36.106249: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll Traceback (most recent call last): File "L:\BERT-BILSTM-CRF-NER-Pytorch-Chinese-main\torch_ner\source\predict.py", line 216, in print(get_entities_result(sent)) File "L:\BERT-BILSTM-CRF-NER-Pytorch-Chinese-main\torch_ner\source\predict.py", line 24, in get_entities_result sentence_list, predict_labels = predict(query, path) File "L:\BERT-BILSTM-CRF-NER-Pytorch-Chinese-main\torch_ner\source\predict.py", line 59, in predict tokenizer = BertTokenizer.from_pretrained(model_path) File "C:\Users\LENOVO\anaconda3\envs\BERT-BILSTM-CRF-NER-Pytorch-Chinese-main\lib\site-packages\transformers\tokenization_utils_base.py", line 1647, in from_pretrained fast_tokenizer_file = get_fast_tokenizer_file( File "C:\Users\LENOVO\anaconda3\envs\BERT-BILSTM-CRF-NER-Pytorch-Chinese-main\lib\site-packages\transformers\tokenization_utils_base.py", line 3408, in get_fast_tokenizer_file all_files = get_list_of_files(path_or_repo, revision=revision, use_auth_token=use_auth_token) File "C:\Users\LENOVO\anaconda3\envs\BERT-BILSTM-CRF-NER-Pytorch-Chinese-main\lib\site-packages\transformers\file_utils.py", line 1686, in get_list_of_files model_info = HfApi(endpoint=HUGGINGFACE_CO_RESOLVE_ENDPOINT).model_info( File "C:\Users\LENOVO\anaconda3\envs\BERT-BILSTM-CRF-NER-Pytorch-Chinese-main\lib\site-packages\huggingface_hub\hf_api.py", line 248, in model_info r.raise_for_status() File "C:\Users\LENOVO\anaconda3\envs\BERT-BILSTM-CRF-NER-Pytorch-Chinese-main\lib\site-packages\requests\models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/output/20221219153051
> 
> 由于是刚入门的小白第一次跑项目，因此不太了解以上的报错，请大神指教，谢谢！
------------------------------------------------------------------------------------------------------------
确认几个事情：
1，本地模型地址正确吗？
2，网络正确吗？没有科学上网的话好像连不上Hugging Face Hub
     2.1 要么科学上网
     2.2 要么换成国内镜像 https://blog.csdn.net/weixin_40959890/article/details/140319652?spm=1001.2014.3001.5501
     
3，确认本地模型文件齐全，不缺少文件

如果还有问题，可以把你的目录文件详细结构和相关代码贴上来
